version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 2
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run:
          command: |
            circleci tests split < /"04 Parallelism"/src

workflows:
  version: 2
  test:
    jobs:
      - test